### ISSUE TITLE
Make ssl key- & truststore password configurable

### ISSUE THREAD

**Issue by RVanhuysseXenit** [xenit-eu/docker-solr#30]
replace hardcoded values with variables

[DOCKER-343](https://xenitsupport.jira.com/browse/DOCKER-343)

**Comment by anghelutar** [comment]
It did not work by setting SSL_KEY_STORE_PASSWORD?

**Comment by RVanhuysseXenit** [comment]
I just now tried reproducing the issue in the project where it was discovered, but it didnt reoccur.
Maybe the problem was caused by some change while getting the dev setup running.

I'll close the issue once i've ran a test in a clean project and it doesn't reoccur.
If it's reproducable I'll add the setup to the issue and put forth a fix.
