### ISSUE TITLE
Please create a multiarch image with support for Apple M1 CPU

### ISSUE THREAD

**Issue by trycoon** [xenit-eu/docker-solr#71]
I fail to start this image on a modern Apple Macbook Pro with M1 (aarch64/arm64) chipset, on a Amd64(x64) architecture it works great.

` docker-solr % docker run --rm -e CORES_TO_TRACK=alfresco -e JAVA_XMS=2G -e JAVA_XMX=2G -e ALFRESCO_HOST=localhost -e ALFRESCO_PORT_SSL=8443 -e ARCHIVE_ENABLE_TRACKING=false -e ARCHIVE_INDEX_CONTENT=false xenit/alfresco-solr6-xenit/master:2.0.3

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
> Executing /docker-entrypoint.d/80-java-opts.sh
-- collecting JAVA_OPTS_XMS=-Xms2G
-- collecting JAVA_OPTS_XMX=-Xmx2G
-- collecting JAVA_OPTS_JMX=-Dcom.sun.management.jmxremote.authenticate=false                 -Dcom.sun.management.jmxremote.local.only=false                 -Dcom.sun.management.jmxremote.ssl=false                 -Dcom.sun.management.jmxremote                 -Dcom.sun.management.jmxremote.rmi.port=5000                 -Dcom.sun.management.jmxremote.port=5000                 -Djava.rmi.server.hostname=0.0.0.0
Result: JAVA_OPTS=-Xms2G -Xmx2G -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.rmi.port=5000 -Dcom.sun.management.jmxremote.port=5000 -Djava.rmi.server.hostname=0.0.0.0
> Executing /docker-entrypoint.d/89-check-validity.sh
> Executing /docker-entrypoint.d/91-healthcheck.sh
Solr init healthcheck start
Importing keystore /opt/alfresco-search-services/solrhome/keystore/ssl.repo.client.keystore to /opt/alfresco-search-services/solrhome/keystore/browser.p12...

Warning:
<ssl.repo> uses the SHA1withRSA signature algorithm which is considered a security risk. This algorithm will be disabled in a future update.
<ssl.repo> uses a 1024-bit RSA key which is considered a security risk. This key size will be disabled in a future update.
Solr init healthcheck end
> Executing /docker-entrypoint.d/92-init-solr.sh
Solr init start
Creating Alfresco core=alfresco in /opt/alfresco-search-services/solrhome/alfresco
Creating Solr backup directory in /opt/alfresco-search-services/data/solr6Backup/alfresco 
Solr init done
> Executing /docker-entrypoint.d/93-restore-from-backup.sh
Solr restore from backup start
No index backup restore requested, exiting
Solr restore from backup end
> Executing /docker-entrypoint.d/95-init-solr-micrometer-metrics.sh
> Starting CMD: ${SOLR_INSTALL_HOME}/startup.sh
> exec /opt/alfresco-search-services/startup.sh
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x51d840, 0x9)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.newosproc(0xc82002e000, 0xc82003dfc0)
	/usr/local/go/src/runtime/os1_linux.go:149 +0x18c
runtime.newm(0x54abb0, 0x0)
	/usr/local/go/src/runtime/proc.go:1516 +0x135
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:125 +0x2c
runtime.systemstack(0x5b9400)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820028770 sp=0xc820028768
runtime.main()
	/usr/local/go/src/runtime/proc.go:126 +0x62 fp=0xc8200287c0 sp=0xc820028770
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200287c8 sp=0xc8200287c0`

**Comment by trycoon** [comment]
An example:
https://github.com/aborroy/alfresco-dockerx-builder

**Comment by thijslemmens** [comment]
Hello @trycoon 

Thanks for posting this issue.
To be honest, I don't think support for ARM64 will be high on our priority list anytime soon. We just don't use it at the moment and we have no developers on a Mac either.
We'd be happy to accept a PR if it does not over-complicate our build process.

kind regards

Thijs

**Comment by trycoon** [comment]
Thanks for your consideration! Since we use Alfresco for your CMS system, most of our developers are on a Mac, but I have done a custom fork of your repo taking the pieces we need. And its all working well, so I'm closing this issue.

Many thanks!
